[workspace]
authors = ["Mark Servilla <mark.servilla@gmail.com>"]
channels = ["conda-forge"]
name = "tocker"
platforms = ["linux-64"]
version = "0.0.1"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
daiquiri = ">=3.0.0,<4"
click = ">=8.2.1,<9"
pixi-pycharm = ">=0.0.8,<0.0.9"
pip = ">=25.2,<26"
